language: python

python:
 - "3.5"
 - "3.6"
 - "3.7"
 - "3.8"

jobs:
  include:
    - stage: Build Docs
      python: "3.7"
      script: cd docs/scripts && bash generateFromDocstrings.sh

install: pip install -r requirements_dev.txt

script: pytest