site_name: pyautogit Documentation
repo_url: https://github.com/jwlodek/pyautogit/
copyright: 2020 - Jakub Wlodek
nav:
  - Home: index.md
  - Installation: install.md
  - Basic Usage: usage.md
  - Repo Select Screen: repo_select.md
  - Repo Control Screen: repo_control.md
  - For Developers:
    - Introduction: developers.md
    - PyAutogitManager: DocstringGenerated/Pyautogit.md
    - Screen Manager: DocstringGenerated/ScreenManager.md
    - Repo Select: DocstringGenerated/RepoSelectScreen.md
    - Repo Control: DocstringGenerated/RepoControlScreen.md
    - Commands: DocstringGenerated/Commands.md
    - Settings Screen: DocstringGenerated/SettingsScreen.md
    - Editor Screen: DocstringGenerated/InternalEditorScreen.md
    - Logger: DocstringGenerated/Logger.md
    - Metadata Manager: DocstringGenerated/MetadataManager.md
  - About: about.md
theme: readthedocs
